from enum import Enum


class ConversationState(str, Enum):
    START = "START"
    ASK_FEEDBACK = "ASK_FEEDBACK"
    PRE_FEEDBACK_ANALYSIS = "PRE_FEEDBACK_ANALYSIS"
    ISSUE_DETECTION = "ISSUE_DETECTION"
    ISSUE_HANDLING = "ISSUE_HANDLING"
    ASK_RATING = "ASK_RATING"
    HANDLE_VAGUE_RATING = "HANDLE_VAGUE_RATING"
    CLASSIFY_INTENT = "CLASSIFY_INTENT"
    POSITIVE_FLOW = "POSITIVE_FLOW"
    NEGATIVE_FLOW = "NEGATIVE_FLOW"
    NEUTRAL_FLOW = "NEUTRAL_FLOW"
    ANALYZE_FEEDBACK = "ANALYZE_FEEDBACK"
    CLASSIFY_ISSUE_TYPE = "CLASSIFY_ISSUE_TYPE"
    STORE_FEEDBACK = "STORE_FEEDBACK"
    FEEDBACK_CONTINUE = "FEEDBACK_CONTINUE"
    END = "END"


class MessageRole(str, Enum):
    USER = "user"
    ASSISTANT = "assistant"
